# Generated by Django 5.2.17 on 2026-10-05 11:58

import django.utils.timezone
from django.db import migrations, models
from django.utils import timezone


def migrate_legacy_django_users(apps, schema_editor):
    """Move legacy auth_user records into the unified users table on MySQL."""
    connection = schema_editor.connection
    if connection.vendor != "mysql":
        return

    with connection.cursor() as cursor:
        cursor.execute(
            "SELECT CONSTRAINT_NAME FROM information_schema.KEY_COLUMN_USAGE "
            "WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'django_admin_log' "
            "AND COLUMN_NAME = 'user_id' AND REFERENCED_TABLE_NAME IS NOT NULL"
        )
        foreign_keys = [row[0] for row in cursor.fetchall()]
        for foreign_key in foreign_keys:
            cursor.execute(f"ALTER TABLE django_admin_log DROP FOREIGN KEY `{foreign_key}`")

        cursor.execute("SHOW TABLES LIKE 'auth_user'")
        legacy_table_exists = cursor.fetchone() is not None
        if legacy_table_exists:
            cursor.execute(
                "SELECT id, password, last_login, is_superuser, username, first_name, last_name, "
                "email, is_staff, is_active, date_joined FROM auth_user"
            )
            legacy_users = cursor.fetchall()
        else:
            legacy_users = []

    for (legacy_id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined) in legacy_users:
        email = (email or f"{username}@legacy.local").lower()
        name = f"{first_name} {last_name}".strip() or username or email.split("@")[0]
        role = "admin" if is_staff or is_superuser else "customer"
        with connection.cursor() as cursor:
            cursor.execute("SELECT id FROM users WHERE email = %s", [email])
            existing = cursor.fetchone()
            if existing:
                customer_id = existing[0]
                cursor.execute(
                    "UPDATE users SET name=%s, password=%s, role=%s, is_active=%s, is_staff=%s, "
                    "is_superuser=%s, last_login=%s, date_joined=%s WHERE id=%s",
                    [name, password, role, is_active, bool(is_staff or is_superuser), is_superuser,
                     last_login, date_joined or timezone.now(), customer_id],
                )
            else:
                cursor.execute(
                    "INSERT INTO users (name, email, password, password_hash, role, auth0_id, avatar_url, "
                    "is_active, is_staff, is_superuser, email_verified, last_login, last_login_at, "
                    "date_joined, created_at, updated_at) "
                    "VALUES (%s, %s, %s, NULL, %s, NULL, NULL, %s, %s, %s, %s, %s, NULL, %s, %s, %s)",
                    [name, email, password, role, is_active, bool(is_staff or is_superuser), is_superuser,
                     False, last_login, date_joined or timezone.now(), timezone.now(), timezone.now()],
                )
                customer_id = cursor.lastrowid
            cursor.execute("UPDATE django_admin_log SET user_id = %s WHERE user_id = %s", [customer_id, legacy_id])

    with connection.cursor() as cursor:
        cursor.execute("ALTER TABLE django_admin_log MODIFY user_id BIGINT NOT NULL")
        cursor.execute(
            "ALTER TABLE django_admin_log ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_users_id "
            "FOREIGN KEY (user_id) REFERENCES users(id)"
        )


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['-created_at'], 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AddField(
            model_name='customer',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='customer',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
        migrations.AddField(
            model_name='customer',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='customer',
            name='password',
            field=models.CharField(blank=True, default='!', max_length=128),
        ),
        migrations.AddField(
            model_name='customer',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.RunPython(migrate_legacy_django_users, migrations.RunPython.noop),
    ]
