import { ArrowRight, ShoppingBag, Trash2 } from "lucide-react";
import { FormEvent, useCallback, useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { api, formatMoney } from "../api";
import { useSession } from "../auth/SessionContext";
import type { Cart } from "../types";

export default function CartPage() {
  const { getToken } = useSession(); const [cart, setCart] = useState<Cart>(); const [checkout, setCheckout] = useState(false); const [error, setError] = useState("");
  const load = useCallback(async () => { const token = await getToken(); setCart(await api<Cart>("/cart", {}, token)); }, [getToken]);
  useEffect(() => { load(); }, [load]);
  const change = async (id: number, quantity: number) => { const token = await getToken(); if (quantity < 1) await api(`/cart/items/${id}`, { method: "DELETE" }, token); else await api(`/cart/items/${id}`, { method: "PATCH", body: JSON.stringify({ quantity }) }, token); await load(); };
  const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); setError(""); const data = new FormData(event.currentTarget); const address = Object.fromEntries(data.entries()); try { const token = await getToken(); const result = await api<{ checkout_url: string }>("/checkout/create-session", { method: "POST", body: JSON.stringify({ shipping_address: address }) }, token); window.location.assign(result.checkout_url); } catch (err) { setError(err instanceof Error ? err.message : "Checkout failed"); } };
  if (!cart) return <div className="page-state">Loading your cart…</div>;
  if (!cart.items.length) return <section className="empty-state page"><ShoppingBag size={42}/><h1>Your cart is waiting</h1><p>Choose something useful from the collection.</p><Link className="button primary" to="/">Browse products</Link></section>;
  return <section className="content-page"><header className="page-heading"><p className="eyebrow">Your selection</p><h1>Shopping cart</h1><p>{cart.item_count} item{cart.item_count !== 1 && "s"} reserved when checkout begins.</p></header><div className="cart-layout"><div className="cart-list">{cart.items.map(item => <article className="cart-item" key={item.id}><div className="cart-thumb">{item.image_url ? <img src={item.image_url} alt=""/> : item.name.charAt(0)}</div><div><h3>{item.name}</h3><p>{item.sku}</p><strong>{formatMoney(item.unit_price, cart.currency)}</strong></div><div className="cart-quantity"><button onClick={() => change(item.id, item.quantity - 1)}>−</button><span>{item.quantity}</span><button disabled={item.quantity >= item.available_stock} onClick={() => change(item.id, item.quantity + 1)}>+</button></div><strong>{formatMoney(item.line_total, cart.currency)}</strong><button className="icon-button" onClick={() => change(item.id, 0)} aria-label="Remove"><Trash2 size={18}/></button></article>)}</div><aside className="summary-card"><p className="eyebrow">Order summary</p><div><span>Subtotal</span><strong>{formatMoney(cart.subtotal, cart.currency)}</strong></div><div><span>Shipping</span><strong>Free</strong></div><hr/><div className="summary-total"><span>Total</span><strong>{formatMoney(cart.subtotal, cart.currency)}</strong></div><button className="button primary full" onClick={() => setCheckout(true)}>Checkout <ArrowRight size={18}/></button><small>Stock is reserved for 30 minutes after checkout begins.</small></aside></div>{checkout && <div className="modal-backdrop"><form className="checkout-modal" onSubmit={submit}><button type="button" className="modal-close" onClick={() => setCheckout(false)}>×</button><p className="eyebrow">Delivery details</p><h2>Where should it go?</h2><div className="field-grid"><label>Recipient<input name="recipient_name" required defaultValue="Demo Customer"/></label><label>Phone<input name="phone" required defaultValue="9876543210"/></label><label className="wide">Address<input name="line1" required defaultValue="12 Market Street"/></label><label className="wide">Address line 2<input name="line2"/></label><label>City<input name="city" required defaultValue="Chennai"/></label><label>State<input name="state" required defaultValue="Tamil Nadu"/></label><label>Postal code<input name="postal_code" required defaultValue="600001"/></label><label>Country<input name="country_code" required defaultValue="IN" maxLength={2}/></label></div>{error && <p className="form-error">{error}</p>}<button className="button primary full">Continue to Stripe test checkout</button></form></div>}</section>;
}
